# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Austin Jingle Bell 5K &ndash; December 11, 2016
description: The Austin Jingle Bell 5k is a great family-oriented run/walk that takes place each December at The Domain in Austin to benefit MADD (Mothers Against Drunk Driving). Each participant is fastened with their own set of bells to give the event it’s signature ‘jingle bell’ atmosphere, not to mention Santa will be in attendance! Bring the whole family and join us in kicking off the month of December with a little Christmas spirit for an important cause.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://austinjinglebell.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems: [bourbon, neat, jekyll-redirect-from]
exclude: ['Gemfile', 'Gemfile.lock']